mod is_cmd_exists_and_executable;
pub(crate) use is_cmd_exists_and_executable::is_cmd_exists_and_executable;

mod is_cmd_exists_in_path_and_executable;
pub(crate) use is_cmd_exists_in_path_and_executable::is_cmd_exists_in_path_and_executable;
